### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by rooklift** [RyanDraves/Halite-II-Bots#1]
When I try to compile this I get an error complaining that [this](https://github.com/RyanDraves/Halite-II-Bots/blob/master/MyBot.cpp#L765) else statement isn't right after an if, due to the presence of [this](https://github.com/RyanDraves/Halite-II-Bots/blob/master/MyBot.cpp#L735) declaration here. It seems like moving that declaration up a few lines is sufficient to solve it?

**Comment by RyanDraves** [comment]
Oops! The actual issue is that I commented out the "bunny ship" navigation correction, the long comment in between, because it was phased out, and it contains the matching if statement. Moving my declaration up works just as well, but I'll go ahead and edit the if statement back in and comment out the code block instead. Thanks for looking through my code!
